services:
    xhprof_listener:
        class: Jns\Bundle\Debug\XHProfBundle\RequestListener
        arguments: [@logger]
        tags:
            - { name: kernel.listener, priority: 0, event: core.request, method: handle}

    data_collector.xhprof:
        class: Jns\Bundle\Debug\XHProfBundle\DataCollector\XHProfDataCollector
        arguments: [@service_container, @logger]
        tags:
            - { name: data_collector, template: "JnsXHProfBundle:Collector:xhprof", id: "xhprof"}
