services:
    xhprof_listener:
        class: Jns\Bundle\XhprofBundle\RequestListener
        arguments: [@logger]
        tags:
            - { name: kernel.listener, priority: 0, event: core.request, method: handle}

    data_collector.xhprof:
        class: Jns\Bundle\XhprofBundle\DataCollector\XhprofDataCollector
        arguments: [@service_container, @logger]
        tags:
            - { name: data_collector, template: "JnsXhprofBundle:Collector:xhprof", id: "xhprof"}
